[project]
authors = [
    { name = "Katherine Rose", email = "kiarc@kiarc.win" },
    { name = "Alexander Joseph" },
    { name = "Joshua Piety" },
]
dependencies = [ 'numpy' ]
description = "Trigonometric functions generalized for parabolas and polygons"
name = "gentrig" # as it would appear on PyPI
readme = "README.md"
requires-python = ">=3.8"
version = "0.1.2"

[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools", "numpy" ]

[tool.cibuildwheel]
build-frontend = "build[uv]"
