name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build compiled wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1
      with:
        python-versions: 'cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312'
    - name: Build sdist
      run: python -m build . --sdist
    - name: Remove non-manylinux wheels
      run: sudo rm dist/gentrig*linux_x86_64*.whl
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
