name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_wheels:
      name: Build wheels on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-13, macos-14]
  
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
  
        - name: Install cibuildwheel
          run: python -m pip install cibuildwheel==2.20.0
  
        - name: Build wheels
          run: python -m cibuildwheel --output-dir wheelhouse
          env:
            # Ignore py36 and py37 because they're not supported, and ignorè 32bit platforms because they don't build
            CIBW_SKIP: cp36-* cp37-* *-win32 *-manylinux_i686
        - name: Upload artifacts
          uses: actions/upload-artifact@v3.2.1-node20
          with:
            name: ${{ matrix.os }}-dist
            path: dist
  build_sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build numpy
    - name: Build sdist
      run: python -m build . --sdist
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: sdist-dist
        path: dist
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Download Linux Dist
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest-dist
          path: dist
      - name: Download macOS 13 Dist
        uses: actions/download-artifact@master
        with:
          name: macos-13-dist
          path: dist
      - name: Download macOS 14 Dist
        uses: actions/download-artifact@master
        with:
          name: macos-14-dist
          path: dist
      - name: Download Windows Dist
        uses: actions/download-artifact@master
        with:
          name: windows-latest-dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    
